# Generated by Django 5.2.6 on 2025-09-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', '남자'), ('Female', '여자')], default=None, max_length=10, null=True),
        ),
    ]
