# Generated by Django 5.2.6 on 2025-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=12345678910, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
