# Generated by Django 5.2.6 on 2025-09-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_info_consent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
