# Generated by Django 5.2.6 on 2025-09-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_created_at_user_role_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_consent_to_receive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='email수신'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_consent',
            field=models.BooleanField(default=True, verbose_name='개인정보처리방침'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sns_consent_to_receive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='sns수신'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_of_use',
            field=models.BooleanField(default=True, verbose_name='이용약관'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_info_consent',
            field=models.BooleanField(verbose_name='개인정보수집'),
        ),
    ]
