# Generated by Django 5.2.6 on 2025-09-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_email_consent_to_receive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privacy_policy_consent',
        ),
    ]
