# Generated by Django 5.2.6 on 2025-10-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='naver_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Naver ID'),
        ),
    ]
