# Generated by Django 5.2.6 on 2025-10-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermissionConsumer',
            new_name='PermissionCustomer',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '관리자'), ('customer', '소비자')], default='customer', max_length=10),
        ),
        migrations.AlterModelTable(
            name='permissioncustomer',
            table='customer_permissions',
        ),
    ]
