# Generated by Django 5.2.6 on 2025-10-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_naver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Naver ID'),
        ),
    ]
