# Generated by Django 5.2.6 on 2025-10-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_permissionconsumer_permissioncustomer_and_more'),
        ('users', '0014_user_naver_id'),
    ]

    operations = [
    ]
