# Generated by Django 5.2.6 on 2025-10-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20251023_1934'),
        ('users', '0015_user_apple_id'),
    ]

    operations = [
    ]
