# Generated by Django 5.2.6 on 2025-09-29 10:35

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.product_image_upload_path),
        ),
    ]
