# Generated by Django 5.2.6 on 2025-10-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_parent'),
        ('products', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, db_table='product_category_cdt', to='categories.category'),
        ),
    ]
